# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Th1gw2OMg2JBtrIOnIKcBmHyDO2nHbG
"""

# =============================================================================
# ANALISIS DATA TIDAL THINGSPEAK SR01 SUNGSANG (Google Colab Version)
# Entry ID 1859+, Interval 10 menit, Deviasi + 4 Plot PNG
# =============================================================================

# Install dependencies (jalankan sekali)
!pip install requests pandas matplotlib numpy pytz -q

import requests
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import pytz
from IPython.display import display, HTML
import warnings
warnings.filterwarnings('ignore')

print("🚀 Google Colab Tidal Analysis SR01 SUNGSANG siap!")

# --- 1. DOWNLOAD DATA DARI THINGSPEAK (Field 2, 8000 latest entries)
print("\n📥 Downloading data dari ThingSpeak...")
url = "https://api.thingspeak.com/channels/3097834/feeds.json?results=8000"
try:
    response = requests.get(url, timeout=30)
    response.raise_for_status()
    data = response.json()
    feeds = data['feeds']
    print(f"✅ Berhasil download {len(feeds)} entries")
except Exception as e:
    print(f"❌ Error: {e}")
    print("Coba manual download JSON dan upload ke Colab")
    raise

# --- 2. BUAT DATAFRAME
print("\n🔄 Processing data...")
df_list = []
jakarta_tz = pytz.timezone('Asia/Jakarta')

for f in feeds:
    if f['field2'] is not None:
        dt = pd.to_datetime(f['created_at']).tz_convert(jakarta_tz)
        df_list.append({
            'datetime': dt,
            'entry_id': int(f['entry_id']),
            'field2': float(f['field2'])
        })

df = pd.DataFrame(df_list).sort_values('datetime').reset_index(drop=True)
print(f"✅ Dataframe: {len(df)} points setelah filter NA")

# --- 3. FILTER MULAI ENTRY_ID = 1859
start_id = 1859
tmp = df[df['entry_id'] >= start_id][['datetime', 'entry_id', 'field2']].reset_index(drop=True)
n = len(tmp)
print(f"✅ Filtered: {n} points mulai entry_id {start_id}")

# --- 4. BANGUN ULANG DATETIME INTERVAL 10 MENIT
start_time_tag = pd.Timestamp("2026-03-01 01:46:02", tz='Asia/Jakarta')
datetime_seq = pd.date_range(start=start_time_tag, freq='10T', periods=n)
# TAMBAH KOLOM field2_neg & hms
extract_data = tmp.copy()
extract_data['datetime'] = datetime_seq
extract_data['hms'] = extract_data['datetime'].dt.strftime('%H:%M:%S')
extract_data['field2_neg'] = extract_data['field2'] * -1

print(f"✅ Rentang waktu: {extract_data['datetime'].min()} → {extract_data['datetime'].max()}")

# --- 5. TAMPILKAN DATA SAMPLE
print("\n📊 SAMPLE DATA (10 pertama):")
display(extract_data[['entry_id', 'datetime', 'hms', 'field2', 'field2_neg']].head(10))

print("\n⏰ HMS INTERVAL 10 MENIT (10 pertama):")
print(extract_data['hms'].head(10).tolist())

# --- 6. ANALISIS INTERVAL
diff_min = pd.Series(np.insert(pd.Series(np.diff(extract_data['datetime'])).dt.total_seconds()/60, 0, np.nan))
extract_data['diff_min'] = diff_min.round(1)
print("\n📈 RINGKASAN INTERVAL (menit):")
print(diff_min.describe())

# --- 7. SIMPAN CSV 1
extract_data.to_csv("field2_tidal_entry1859_2026.csv", index=False)
print("\n💾 CSV 1: field2_tidal_entry1859_2026.csv ✅")

# --- 8. HITUNG DEVIASI
print("\n📊 STATISTIK DEVIASI:")
mean_field2 = extract_data['field2'].mean()
extract_data['field2_deviasi'] = extract_data['field2'] - mean_field2

mean_field2_neg = extract_data['field2_neg'].mean()
extract_data['field2_neg_deviasi'] = extract_data['field2_neg'] - mean_field2_neg

print(f"Field2     Mean: {mean_field2:.3f}, Deviasi range: {extract_data['field2_deviasi'].min():.3f} → {extract_data['field2_deviasi'].max():.3f}")
print(f"Field2_neg Mean: {mean_field2_neg:.3f}")

print("\n📈 SUMMARY DEVIASI:")
print("Field2_deviasi:", extract_data['field2_deviasi'].describe())
print("Field2_neg_deviasi:", extract_data['field2_neg_deviasi'].describe())

# --- 9. SIMPAN CSV 2 (LENGKAP)
extract_data.to_csv("field2_tidal_entry1859_deviasi_2026.csv", index=False)
print("💾 CSV 2: field2_tidal_entry1859_deviasi_2026.csv ✅")

# =============================================================================
# PLOTTING (4 GAMBAR HD PNG)
# =============================================================================

def plot_tidal(ax, data, ycol, title, ylabel, color, mean_line, mean_val):
    ax.plot(data['datetime'], data[ycol], color=color, linewidth=2)
    ax.axhline(mean_line, color='blue', linewidth=3, linestyle='--', alpha=0.8)
    ax.text(0.72, 0.95, f'Mean = {mean_val:.3f}', transform=ax.transAxes,
            color='blue', fontsize=11, bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))
    ax.set_title(title, fontsize=14, pad=20)
    ax.set_xlabel('Waktu (WIB)', fontsize=12)
    ax.set_ylabel(ylabel, fontsize=12)
    ax.grid(True, alpha=0.3)
    ax.tick_params(axis='x', rotation=45)

# PLOT 1: FIELD2 ASLI (Jarak dari Alat)
fig1, ax1 = plt.subplots(figsize=(14, 8))
plot_tidal(ax1, extract_data, 'field2', 'Kurva Pasang Surut (Jarak dari Alat Ukur)',
           'Jarak dari Alat (m)', 'red', mean_field2, mean_field2)
plt.tight_layout()
plt.savefig("plot1_fielddata_dari_alat.png", dpi=150, bbox_inches='tight')
plt.show()
print("🖼️  PLOT 1: plot1_fielddata_dari_alat.png ✅")

# PLOT 2: FIELD2_NEG (Tinggi Muka Air)
fig2, ax2 = plt.subplots(figsize=(14, 8))
plot_tidal(ax2, extract_data, 'field2_neg', 'Kurva Pasang Surut (Tinggi Muka Air)',
           'Tinggi Muka Air (m)', 'red', mean_field2_neg, mean_field2_neg)
plt.tight_layout()
plt.savefig("plot2_field2_neg_entry1859.png", dpi=150, bbox_inches='tight')
plt.show()
print("🖼️  PLOT 2: plot2_field2_neg_entry1859.png ✅")

# PLOT 3: DEVIASI FIELD2 ASLI
fig3, ax3 = plt.subplots(figsize=(14, 8))
plot_tidal(ax3, extract_data, 'field2_deviasi', 'Anomali Jarak dari Alat',
           'Deviasi dari Mean (m)', 'darkgreen', 0, 0)
plt.tight_layout()
plt.savefig("plot3_field2_deviasi_entry1859.png", dpi=150, bbox_inches='tight')
plt.show()
print("🖼️  PLOT 3: plot3_field2_deviasi_entry1859.png ✅")

# PLOT 4: DEVIASI FIELD2_NEG
fig4, ax4 = plt.subplots(figsize=(14, 8))
plot_tidal(ax4, extract_data, 'field2_neg_deviasi', 'Anomali Pasut Real',
           'Deviasi dari Mean (m)', 'darkorange', 0, 0)
ax4.legend(['Deviasi', 'Mean=0'], loc='upper right', fontsize=11)
plt.tight_layout()
plt.savefig("plot4_field2_neg_deviasi_entry1859.png", dpi=150, bbox_inches='tight')
plt.show()
print("🖼️  PLOT 4: plot4_field2_neg_deviasi_entry1859.png ✅")

# --- FINAL SUMMARY
print("\n" + "="*60)
print("🎉 ANALISIS SELESAI!")
print(f"📊 Total data points: {n}")
print(f"⏱️  Durasi: {n*10/60:.1f} jam")
print("💾 Files di-generate:")
print("   • 2 CSV: field2_tidal_entry1859_*.csv")
print("   • 4 PNG: plot[1-4]_*.png")
print("📥 Download dari panel Files (kiri Colab)")
print("="*60)

# Tampilkan link download semua files
from google.colab import files
print("\n⬇️  DOWNLOAD SEMUA FILES:")
files.download("field2_tidal_entry1859_2026.csv")
files.download("field2_tidal_entry1859_deviasi_2026.csv")
# PNG akan muncul di Files panel
